# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Particle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Particle
  pod 'RIBs', :git => 'https://github.com/uber/RIBs', :commit => 'ffc489f00db785c8c0051678393f7aba0d52f1a4'
  pod 'SnapKit', '~> 5.6.0'
  pod 'RxCocoa'
  pod 'KakaoSDK'
  pod 'Kingfisher'

end
post_install do |installer|
    installer.generated_projects.each do |project|
       project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
            end
        end
    end
end